default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("SQL_USER") %>
  password: <%= ENV.fetch("SQL_KEY") %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rep_ani_development

test:
  <<: *default
  database: rep_ani_test

production:
  <<: *default
  database: rep_ani_production
